### ISSUE TITLE
 treesitter makes working on nix files  almost unusable

### ISSUE THREAD

**Issue by mcsimw** [iofq/nvim-treesitter-main#26]
I don't know if it is just me having this problem. But specifically nix files, the parsing is the slowest it has ever been.

Simple files with like 50 lines of code are just fine. A bit of nesting, 200+ lines of code and it is unusable.

Like  if I open the generated.nix file in this repo, the syntax highlighting takes a bit of time to load. Once the file is open, in normal mode it is just fine, as soon as I enter insert mode and start typing, it lags so bad I can't use it, I think a recent revision caused this. I am not sure if it is treesitter itself or just the nix grammar for tree-sitter. I am curious if you have the same issue.

Perhaps tree-sitter needs to be locked to a certain revision for now to resolve this? Or maybe a configuration issue on my end?

**Comment by iofq** [comment]
Hello, 

This appears to have been fixed upstream in https://github.com/nvim-treesitter/nvim-treesitter/pull/8375, which I've just updated this flake to. Please update to the latest commit of this flake and let me know if there's still issues!

**Comment by HeitorAugustoLN** [comment]
As I said in NixOS/nixpkgs#470883, the queries and parser for Nix are still the same as before (before the match -> lua-match thing), so it shouldn't be related to nvim-treesitter.

It should be related to `vim.treesitter.start()`, not sure why though

**Comment by mcsimw** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/8378

this fixed it.

We good!
